### ISSUE TITLE
Java version of Forro?

### ISSUE THREAD

**Issue by BigPanda97** [jedisct1/forro#3]
This project looks very nice, but I would need a Java version of it.
Could you please translate it to Java source code or at least give me some tips on who could do this for me?

Thanks & best regards.

**Comment by jedisct1** [comment]
Forro doesn't have a significant advantage over existing ciphers, and I have no personal interest in a Java implementation.

If you really need one, I can absolutely write it, but as under a contractor agreement, not for free on my limited spare time.

**Comment by BigPanda97** [comment]
> If you really need one, I can absolutely write it, but as under a contractor agreement, not for free on my limited spare time.

That sounds okay for me. How much would it cost?

**Comment by BigPanda97** [comment]
> > If you really need one, I can absolutely write it, but as under a contractor agreement, not for free on my limited spare time.
> 
> That sounds okay for me. How much would it cost?

@jedisct1 (Ping, just for the case if the notification wasn't sent because the issue is already closed.)

**Comment by jedisct1** [comment]
Can you send me an email at `consulting` `@` `libsodium` . `org` ? Thank you!

**Comment by BigPanda97** [comment]
> Can you send me an email at `consulting` `@` `libsodium` . `org` ? Thank you!

@jedisct1 done, I sent you the email yesterday. 👍🏻
